// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdqpakP5uaKVW4bIyODDZ2XcDNnp_cQAA',
    appId: '1:824612013655:web:576d78cf2395bc45db0512',
    messagingSenderId: '824612013655',
    projectId: 'app-tareas-geness',
    authDomain: 'app-tareas-geness.firebaseapp.com',
    storageBucket: 'app-tareas-geness.firebasestorage.app',
    measurementId: 'G-66D3X2MGJY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJg7ttKCUyHEDK-yuLOUjn1FXh6ijh-Zg',
    appId: '1:824612013655:android:7a568a43d8cdaa82db0512',
    messagingSenderId: '824612013655',
    projectId: 'app-tareas-geness',
    storageBucket: 'app-tareas-geness.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs-yuPQBfJhzhbtCIj_dFevRjmRFiW3gM',
    appId: '1:824612013655:ios:c7bc49ffab5d856ddb0512',
    messagingSenderId: '824612013655',
    projectId: 'app-tareas-geness',
    storageBucket: 'app-tareas-geness.firebasestorage.app',
    iosBundleId: 'com.example.appChatFirebase',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs-yuPQBfJhzhbtCIj_dFevRjmRFiW3gM',
    appId: '1:824612013655:ios:c7bc49ffab5d856ddb0512',
    messagingSenderId: '824612013655',
    projectId: 'app-tareas-geness',
    storageBucket: 'app-tareas-geness.firebasestorage.app',
    iosBundleId: 'com.example.appChatFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdqpakP5uaKVW4bIyODDZ2XcDNnp_cQAA',
    appId: '1:824612013655:web:1f432e41a249aeb5db0512',
    messagingSenderId: '824612013655',
    projectId: 'app-tareas-geness',
    authDomain: 'app-tareas-geness.firebaseapp.com',
    storageBucket: 'app-tareas-geness.firebasestorage.app',
    measurementId: 'G-18209M8RYB',
  );
}
